title: Automatic 3D Atom Mapping of Elementary Reaction: citations
description: Citation page for the Automatic 3D Atom Mapping of Elementary Reaction poster.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
